### ISSUE TITLE
Add HKN Event Calendar + FB embed to another tab

### ISSUE THREAD

**Issue by D1o0g9s** [HKN-UCSD/hkn-member-portal#10]
Calendar: 
<iframe src="https://calendar.google.com/calendar/embed?src=v90k4miuerv8iemlu0c3gaq968%40group.calendar.google.com&ctz=America%2FLos_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

FB (hknucsd): 
https://developers.facebook.com/docs/plugins/page-plugin/

**Comment by AneeshJalan** [comment]
Issue resolved by @AneeshJalan .
