### ISSUE TITLE
Run prettier on PR

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-member-portal#103]
We need to figure out how to not let people push in non-prettified code

**Comment by thaigillespie** [comment]
Do the pre-commit hooks not resolve this already? And ik what happened yesterday but still, don't ppl just need to run 'npm install' to get that set up?

**Comment by godwinpang** [comment]
yes and no - I think lintstaged doesn't auto install the git precommit hooks
doesn't hurt to just redo what we did over at the hkn-server repo and run prettier --check :)

**Comment by thaigillespie** [comment]
Oh oops, I was thinking this was on hkn-server when I wrote that comment. I'll make the changes
