### ISSUE TITLE
Add master branch protection rule 

### ISSUE THREAD

**Issue by kelvinluime** [HKN-UCSD/hkn-member-portal#11]
![image](https://user-images.githubusercontent.com/24837420/63900155-7d993680-c9b4-11e9-8514-38c6c717c787.png)

Since there are currently no DevOps practices and staging environment set up, I suggest having above protection rules on master branch to require 1 code owner to review pull request, which can make sure the code in master branch always builds successfully. I can always test new code as soon as any new pull request appears for now.

**Comment by kelvinluime** [comment]
@D1o0g9s

**Comment by D1o0g9s** [comment]
Done.
