### ISSUE TITLE
Sign Up screen is clipped on phone

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-member-portal#140]
**Describe the bug**
The sign up screen is horizontally clipped on an iPhone7 due to hardcoded min widths. 

**To Reproduce**
1. Go to staging.hknucsd.com/signup

**Expected behavior**
Expected whole screen to be visible

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: Doesn't matter here
 - Browser: Chrome

**Comment by godwinpang** [comment]
![IMG_8151](https://user-images.githubusercontent.com/32888985/91201489-58b5cd00-e6b5-11ea-9b2e-fb0c08858145.PNG)

**Comment by godwinpang** [comment]
@thaigillespie https://github.com/HKN-UCSD/hkn-member-portal/blob/6c5e7faf0605e246eea9330f1ee4ce9d324106ff/src/pages/SignUpPage/styles.js#L11

**Comment by godwinpang** [comment]
@thaigillespie https://github.com/HKN-UCSD/hkn-member-portal/blob/6c5e7faf0605e246eea9330f1ee4ce9d324106ff/src/pages/SignUpPage/styles.js#L11

**Comment by godwinpang** [comment]
@thaigillespie https://github.com/HKN-UCSD/hkn-member-portal/blob/6c5e7faf0605e246eea9330f1ee4ce9d324106ff/src/pages/SignUpPage/styles.js#L11

**Comment by godwinpang** [comment]
github on mobile is screwed - anyways, that’s why things are messed up

**Comment by thaigillespie** [comment]
Yeah ik that's why it's like that haha. How do you make it look good without relying on a constant width tho?

**Comment by godwinpang** [comment]
ill make a pr later :)
