### ISSUE TITLE
Frontend openapi integration to start using backend API w/o fetch API

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#142]
Since we know have autogenerated code for openapi on the front end, we can make request to the server without needing to use Fetch API. However, for this to work, we will have to make functions that call the autogenerated code to do the requesting for us (example is in src/services/ApiEvents.ts). Furthermore, we will need to start incorporating these functions into our codebase, which will be a huge task because there is still a lot of firebase things in our FE codebase.

**Comment by godwinpang** [comment]
@thaigillespie close yeah?
