### ISSUE TITLE
Convert as many files in src as we can to using Typescript

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#205]
TS good JS bad so that's why we should do this. Multiple ppl can work on this given that this is a pretty big task

**Comment by thaigillespie** [comment]
Feel free to add yourself to the list of assignees

**Comment by godwinpang** [comment]
LOL just saw this

**Comment by thaigillespie** [comment]
lol u fine

**Comment by godwinpang** [comment]
too vague - can we close for now? might be easier if we had a better plan for ts conversion
