### ISSUE TITLE
Role Based Access Control (RBAC) Version 1

### ISSUE THREAD

**Issue by AneeshJalan** [HKN-UCSD/hkn-member-portal#29]
We need a way to identify who all are inductees, members and officers in HKN and also a way to restrict access of features on the portal based on their role in the organization.

1. Write a script that can modify roles of existing users. Probably take in a list of users (emails) and a role that needs to be assigned to these users. Roles are "Officer", "Member", "Inductee". This script will come handy when we want to officially induct people into HKN (leading to a change of role form "Inductee" to "Member"), or when promoting/demoting a "Member" to an "Officer" role.
2. Have a way of restricting/providing access to content on the portal based on a user's role.

**Comment by AimeeShao** [comment]
Write Python cloud function that changes user role using setCustomClaim
- Check auth of incoming request (needs officer)
- Invoked via HTTP
- Invoke function below for changing user's doc
Create a separate function for changing user's doc
Write script that changes batch for inductees to members
- Reads in text file
- For each email: Invokes the Python cloud function

**Comment by godwinpang** [comment]
Done
