### ISSUE TITLE
Figure out a better way to store and implement whitelist

### ISSUE THREAD

**Issue by kelvinluime** [HKN-UCSD/hkn-member-portal#4]
Only emails on the whitelist are able to sign up for an account in the portal. Accounts will be automatically deleted if signed up with an email not on the whitelist. The whitelist is stored directly in the functions/index.js that is executed by Cloud Functions:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const db = admin.firestore();
const settings = { timestampsInSnapshots: true };
db.settings(settings);

const whitelist = new Set([
...emails
```

However, here are some disadvantages for this approach:
1. Hard to add new member emails to whitelist
2. Emails are exposed in this public repository 

It would be nice if one can come up with better approach to implement the whitelist.

**Comment by AneeshJalan** [comment]
Move to other repo.

**Comment by godwinpang** [comment]
Will do after redesigning IAM flow for inductees etc.

**Comment by godwinpang** [comment]
Ok @AneeshJalan I think we're done here?
