### ISSUE TITLE
Rewrite the sign up page completely

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#62]
Rewrite the code for sign up page completely so it's better. 

Current additional feature(s) to add are:
  - Info form: This form is one single form that the user will fill in before getting to the email
    confirmation step in the sign up process. The form will be made to collect:
      - Last name
      - First name
      - Email
      - Password
      - Major 
      - Graduation date

**Comment by godwinpang** [comment]
just fyi - this issue also encompasses a rewrite of the sign up page

**Comment by godwinpang** [comment]
here's your wire frame

can you split 6 6 for the top row and like either 7 5 or 8 4 for the last row

![Sign Up](https://user-images.githubusercontent.com/32888985/85217387-08349300-b345-11ea-919a-530839baccd5.jpg)

**Comment by thaigillespie** [comment]
This is pog tysm
