### ISSUE TITLE
Modal/Pop-up for after signing up for new sign up page

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#71]
Modals/Pop-ups right after the user filled in all needed information and clicked "Sign Up". 

This modal should just ask if the user is happy with what they inputted in the sign up form. If yes, then we proceed to send the inputted data to the sign up endpoint to sign the user up; otherwise, close the modal.

**Comment by godwinpang** [comment]
we should perhaps break this into reusable modals - would be nice to give them some guidance

**Comment by thaigillespie** [comment]
Should I put in some guides by editing the original comment I made? If not, where should I put the guides?

**Comment by godwinpang** [comment]
idk anywhere you can link them to is fine
