### ISSUE TITLE
Sort startDate and endDate by date, not by string, in List view of Calendar

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#73]
startDate and endDate in the List view of Calendar can currently be sorted by string (lexicographically). We want to change it so that startDate and endDate are sorted by the actual date that they hold.

**Comment by thaigillespie** [comment]
Bada bing, bada boom

https://github.com/HKN-UCSD/hkn-member-portal/commit/7bc05227d987160ba854646e22335375f3174512

**Comment by godwinpang** [comment]
can we close issues on PR approval instead? thanks

**Comment by thaigillespie** [comment]
Oh oops sorry got it :p

**Comment by godwinpang** [comment]
u did this already yeah? Imma close it
