### ISSUE TITLE
Fix old RBAC stuff that broke with the db migration

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-member-portal#83]

**Comment by godwinpang** [comment]
https://github.com/HKN-UCSD/hkn-member-portal/blob/master/src/pages/InducteePointsPage/index.js#L53

**Comment by godwinpang** [comment]
@thaigillespie I can still do this but it might take me a while - if you're still searching for issues it'd be nice if you could take this on. If you want to write the public facing non-affiliates form then that's fine with me as well

**Comment by thaigillespie** [comment]
I can tackle both as well.
