### ISSUE TITLE
Turn off sourcemaps in build pipeline

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-member-portal#89]
Our sourcemaps are broken anyways - just remove them

**Comment by thaigillespie** [comment]
https://create-react-app.dev/docs/advanced-configuration/ Apparently we can just put GENERATE_SOURCEMAP=false in our .env file and it should be good.

**Comment by thaigillespie** [comment]
Fixed by adding GENERATE_SOURCEMAP=false to list of env vars on netlify and redeploying.
