### ISSUE TITLE
Consolidate with prod db

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-member-portal#90]
As title - we've deviated hella from the prod db schema and there's gonna be a time where we should consolidate what we have in the dev db with what's in prod rn

**Comment by thaigillespie** [comment]
Okay so for this one, I'm planning to write a nodejs script to bring stuff from prod db to dev db. The things I'm planning to get from prod db to dev db are:
    - "users" collection: Here, I think we should grab fields "email", "role_id" (converts to role string for dev db), "resumeFilename", and perhaps "resumeDownloadURL" (I frankly don't remember in detail the thing with changing how we store resume download url and resume filename during our meeting, I think for resume filename, use their name/email (??). Also, we won't be having first name, last name, graduation year, and major for the user docs that we are moving from prod db to dev db, so what do we do about that?
    - "roles" collection: No need to bring this over, since I'll be using this just to convert role_id (prod db) -> role string (dev db).
    - "pointRewardType" collection: Absolutely no need to bring this over since we already have it in dev db lol.

Let me know if I'm understanding this correctly. And I think I should finish this issue first before moving on to writing a new resume upload service.

**Comment by thaigillespie** [comment]
This means that I might have to create a new repo just to do this, just like when I wrote the script to generate mock event data.

**Comment by godwinpang** [comment]
yeah I think you got it for now. I don't know how you'd design the file upload service yet so we could frankly just leave the resumeFilename + resumeDownloadURL + resumeTimestamp fields as is until we figure out how we want to design resume storage

other things look good :)

**Comment by thaigillespie** [comment]
@godwinpang Thanks for your response. I do still want to ask this though: What do we do about these new users coming into dev db from prod db in terms of first+lastname, major and graduation year? Should we just not care about those fields for these user docs from prod db?

**Comment by thaigillespie** [comment]
@godwinpang Thanks for your response. I do still want to ask this though: What do we do about these new users coming into dev db from prod db in terms of first+lastname, major and graduation year? Should we just not care about those fields for these user docs from prod db?

**Comment by godwinpang** [comment]
great question - we never collected those fields in the first place (at least from the portal)
I'd say we can leave those fields empty for now so empty strings should do the trick

I'm 100% sure that info is in a spreadsheet somewhere so later on if we care we can always populate the db again

**Comment by godwinpang** [comment]
closing - moving to backend repo
