### ISSUE TITLE
Add readonly support for TextField

### ISSUE THREAD

**Issue by thaigillespie** [HKN-UCSD/hkn-member-portal#91]

**Comment by godwinpang** [comment]
Just to clarify - readonly TextFields

**Comment by godwinpang** [comment]
Actually, could we possibly extend this ticket to have generic textfields/dropdowns that support readonly mode? This would make life so much easier for me

**Comment by thaigillespie** [comment]
Is that what we discussed on slack? I'm planning to just have it like this: 

If readOnly is true, then render MUI's TextField. If readOnly is false, then render Formik's Field

**Comment by godwinpang** [comment]
yes sorta - for my stuff I need to render some raw text fields though(aka not major nor year) and would love to see a readOnly prop for that

**Comment by thaigillespie** [comment]
So they would be separate TextFields and not dropdowns then?

**Comment by thaigillespie** [comment]
Like a separate TextField can be made then if you want to just have some raw text fields for your use case. I don't think dropdowns need readonly support, since readonly is a text field anyway. In a form, you tend to want the user to input something, unless there is some prefilled information that the user cannot edit (then it would just be a textfield and not a dropdown).

**Comment by godwinpang** [comment]
yeah now that you bring it up probably just a textfield then

**Comment by godwinpang** [comment]
do you want to lump it in with your PR and put them all in the same folder or sth? thought it would be easier for you to do it since you'd have a function to get the props already

**Comment by thaigillespie** [comment]
Yeah that's fine. I'll rename the folder or something since it won't be containing just dropdowns now.

**Comment by godwinpang** [comment]
lit ty 🔥
